-- RentMate Database Schema

-- 1. Properties Table
CREATE TABLE public.properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address TEXT NOT NULL,
    city TEXT,
    price NUMERIC,
    rooms INTEGER,
    status TEXT DEFAULT 'פנוי', -- 'Available'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tenants Table
CREATE TABLE public.tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    id_number TEXT,
    email TEXT,
    phone TEXT,
    property_address TEXT, -- Linking by address string for now to match local DB simple structure, ideally foreign key to properties(id)
    status TEXT DEFAULT 'פעיל',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Contracts Table
CREATE TABLE public.contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_address TEXT,
    tenant_name TEXT,
    start_date DATE,
    end_date DATE,
    rent_amount NUMERIC,
    payment_frequency TEXT, -- 'monthly', 'quarterly'
    status TEXT DEFAULT 'פעיל',
    file_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Files Metadata Table (Files content should ideally go to Supabase Storage, but this tracks them)
CREATE TABLE public.files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT REFERENCES public.contracts(id),
    name TEXT,
    type TEXT,
    size INTEGER,
    url TEXT, -- Path to Storage bucket
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Enable Row Level Security (RLS)
-- For now, we allow public access to make it work easily for the demo. 
-- IN PRODUCTION: You must policies to restrict access to authenticated users only.
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;

-- Open Access Policy (Dev Mode)
CREATE POLICY "Public Access" ON public.properties FOR ALL USING (true);
CREATE POLICY "Public Access" ON public.tenants FOR ALL USING (true);
CREATE POLICY "Public Access" ON public.contracts FOR ALL USING (true);
CREATE POLICY "Public Access" ON public.files FOR ALL USING (true);
